### PR TITLE
Add description field to NLC classification

### PR DESCRIPTION
**Pull request by jlpadilla**
Resolves issue #11 .

A related PR issued for `hubot-ibmcloud-nlc` here https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/pull/16

### CODE REVIEW

**Comment by normanb** [comment]
@jlpadilla why not just add the description to the by target query? It looks like we are making two queries when we could just make one.

**Comment by jlpadilla** [comment]
@normanb Made the suggested change to reuse the `byTarget` view.  Coverage decreased because I deleted some lines, not sure what to do about the Coveralls failure.

**Comment by normanb** [comment]
@jlpadilla I think

https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib/pull/12/files#diff-3d7cb916bd4257e953a286019baa35b1R102

is redundant, we don't need to add to the API module, the description can be added to the emit target object - https://github.com/ibm-cloud-solutions/hubot-ibmcloud-cognitive-lib/pull/12/files#diff-3d7cb916bd4257e953a286019baa35b1R102

Also in the view definition you are emitting doc._id in the value array, this adds to the index size, it isn't required as it is also the key. It can be be set to null, or not set at all.

**Comment by normanb** [comment]
+1

**Pull request merged**
